scalar Date

type Comment {
  id: ID!
  body: String!
  author: User!
  createdAt: Date!
}

type Post {
  id: ID!
  caption: String
  media: String
  likes: Int!
  author: User!
  comments: [Comment]!
}

input NewPostInput {
  caption: String
  media: String
}

input AddCommentInput {
  id: ID!
  body: String!
}

extend type Query {
  post(input: ID!): Post!
  posts: [Post]!
  myPosts: [Post]!
}

extend type Mutation {
  newPost(input: NewPostInput): Post!
  increasePostLikes(input: ID!): Post!
  decreasePostLikes(input: ID!): Post!
  addComment(input: AddCommentInput!): Post!
} 