
type User {
  id: ID!
  name: String!
  username: String!
  email: String!
  avatar: String
}

input NewUserInput {
  name: String!
  username: String!
  email: String!
  password: String!
  avatar: String
}

input UpdateUserInput {
  id: ID!
  name: String
  username: String
  email: String
  password: String
  avatar: String
}

input SignInInput {
  email: String
  username: String
  password: String!
}

type AuthPayload {
  token: String!
}

type Query {
  user(input: ID!): User!
  users: [User!]!
}

type Mutation {
  updateUser(input: UpdateUserInput!): User!
  signUp(input: NewUserInput!): AuthPayload!
  signIn(input: SignInInput!): AuthPayload!
}


