
type User {
  id: ID!
  name: String!
  username: String!
  email: String!
  avatar: String
}

input NewUserInput {
  name: String!
  username: String!
  email: String!
  password: String!
  avatar: String
}

type LoginUserInput {
  username: String!
  password: String!
}

type AuthPayload {
  token: String!
}

type Query {
  user(input: ID!): User!
  users: [User]!
}

type Mutation {
  signUp(input: NewUserInput!): AuthPayload!
}


